export const JurisdictionEnum = Object.freeze({
  FEDERAL: { name: "federal", readable: "Federal" },
  ALABAMA: { name: "alabama", readable: "AL" },
  ALASKA: { name: "alaska", readable: "AK" },
  ARIZONA: { name: "arizona", readable: "AZ" },
  ARKANSAS: { name: "arkansas", readable: "AR" },
  CALIFORNIA: { name: "california", readable: "CA" },
  COLORADO: { name: "colorado", readable: "CO" },
  CONNECTICUT: { name: "connecticut", readable: "CT" },
  DELAWARE: { name: "delaware", readable: "DE" },
  FLORIDA: { name: "florida", readable: "FL" },
  GEORGIA: { name: "georgia", readable: "GA" },
  HAWAII: { name: "hawaii", readable: "HI" },
  IDAHO: { name: "idaho", readable: "ID" },
  ILLINOIS: { name: "illinois", readable: "IL" },
  INDIANA: { name: "indiana", readable: "IN" },
  IOWA: { name: "iowa", readable: "IA" },
  KANSAS: { name: "kansas", readable: "KS" },
  KENTUCKY: { name: "kentucky", readable: "KY" },
  LOUISIANA: { name: "louisiana", readable: "LA" },
  MAINE: { name: "maine", readable: "ME" },
  MARYLAND: { name: "maryland", readable: "MD" },
  MASSACHUSETTS: { name: "massachusetts", readable: "MA" },
  MICHIGAN: { name: "michigan", readable: "MI" },
  MINNESOTA: { name: "minnesota", readable: "MN" },
  MISSISSIPPI: { name: "mississippi", readable: "MS" },
  MISSOURI: { name: "missouri", readable: "MO" },
  MONTANA: { name: "montana", readable: "MT" },
  NEBRASKA: { name: "nebraska", readable: "NE" },
  NEVADA: { name: "nevada", readable: "NV" },
  NEW_HAMPSHIRE: { name: "new-hampshire", readable: "NH" },
  NEW_JERSEY: { name: "new-jersey", readable: "NJ" },
  NEW_MEXICO: { name: "new-mexico", readable: "NM" },
  NEW_YORK: { name: "new-york", readable: "NY" },
  NORTH_CAROLINA: { name: "north-carolina", readable: "NC" },
  NORTH_DAKOTA: { name: "north-dakota", readable: "ND" },
  OHIO: { name: "ohio", readable: "OH" },
  OKLAHOMA: { name: "oklahoma", readable: "OK" },
  OREGON: { name: "oregon", readable: "OR" },
  PENNSYLVANIA: { name: "pennsylvania", readable: "PA" },
  RHODE_ISLAND: { name: "rhode-island", readable: "RI" },
  SOUTH_CAROLINA: { name: "south-carolina", readable: "SC" },
  SOUTH_DAKOTA: { name: "south-dakota", readable: "SD" },
  TENNESSEE: { name: "tennessee", readable: "TN" },
  TEXAS: { name: "texas", readable: "TX" },
  UTAH: { name: "utah", readable: "UT" },
  VERMONT: { name: "vermont", readable: "VT" },
  VIRGINIA: { name: "virginia", readable: "VA" },
  WASHINGTON: { name: "washington", readable: "WA" },
  WEST_VIRGINIA: { name: "west-virginia", readable: "WV" },
  WISCONSIN: { name: "wisconsin", readable: "WI" },
  WYOMING: { name: "wyoming", readable: "WY" },
});

export const FilingStatusEnum = Object.freeze({
  SINGLE: { name: "single", readable: "Single" },
  MARRIED_FILING_JOINTLY: {
    name: "married-filing-jointly",
    readable: "Married Filing Jointly",
  },
  MARRIED_FILING_SEPARATELY: {
    name: "married-filing-separately",
    readable: "Married Filing Separately",
  },
  HEAD_OF_HOUSEHOLD: {
    name: "head-of-household",
    readable: "Head of Household",
  },
});

export const TimePeriodEnum = Object.freeze({
  FIRST: { name: 0, readable: "1/1 - 3/31" },
  SECOND: { name: 1, readable: "1/1 - 5/31" },
  THIRD: { name: 2, readable: "1/1 - 8/31" },
  FOURTH: { name: 3, readable: "1/1 - 12/31" },
});

export const DeductionTypeEnum = Object.freeze({
  STANDARD: { name: "standard", readable: "Standard" },
  ITEMIZED: { name: "itemized", readable: "Itemized" },
});